### ISSUE TITLE
unable to find package

### ISSUE THREAD

**Issue by li0803** [mathpaquette/IB.CSharpApi#1]
vs 2017:
After run Install-Package IB.CSharpApi, I got below error:

Install-Package : Unable to find package 'IB.CSharpApi'
At line:1 char:1
+ Install-Package IB.CSharpApi
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by mathpaquette** [comment]
@li0803 I'm totally sorry about that and for being late. Since I can only publish one unique version on NuGet and want to match the exact API version, I decided to use pre-release version until I'm complettly sure that my package is perfect to push! So you can instal the package using this command:
`Install-Package IB.CSharpApi -Prerelease`
